kewen:
  base:
    datasource:
      db-url: "liukewensc.mysql.rds.aliyuncs.com:3306/dev_framework_demo"
      username: kewen
      password: Lh19921002
    tenant:
      open: false

spring:
  datasource:
    username: ${kewen.base.datasource.username}
    password: ${kewen.base.datasource.password}
    url: jdbc:p6spy:mysql://${kewen.base.datasource.db-url}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://${kewen.base.datasource.db-url}
    #driver-class-name: com.mysql.cj.jdbc.Driver