logging:
  level:
    org.springframework.security: debug

kewen-framework:
  auth:
    data-range-database-field:
      table-name: sys_auth_data
      dataId-column: data_id
      authority-column: authority
  environment:
    prod: false
  security:
    login:
      login-url: /login
      maximum-sessions: 1
      max-sessions-prevents-login: true