version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: 8
        mavenVersion: 3.9.6
        commands:
          - mvn -B clean package -Dmaven.test.skip=true
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./auth-sample/target/auth-sample-1.0-SNAPSHOT.jar
        settings:
          - certificate: kewen-snapshot
            isRelease: true
            isSnapshot: true
        caches:
          - ~/.m2
        strategy: {}
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: kewen-aliyun
          hostID:
            - 7bd15f80-ec40-48c9-81b9-0b2de3d1540a
        deployArtifact:
          - source: build
            name: auth-sample
            target: ~/gitee_go/deploy
            dependArtifact: BUILD_ARTIFACT
        script:
          - bash ~/kewen-framework-auth/backend/deploy.sh
          - ''
          - echo 'Hello Gitee Go!'
        notify: []
        strategy:
          retry: '0'
