logging:
  level:
    org.springframework.security: debug

kewen-framework:
  auth:
    data-range-database-field:
      table-name: sys_auth_data
      dataId-column: data_id
      authority-column: authority
  security:
    login:
      login-url: /login                 #登录地址
      current-user-url: /currentUser    #当前用户接口地址
      maximum-sessions: 1               #最大session数量
      max-sessions-prevents-login: true # 是否不允许挤下线
      username-parameter: username      # username参数
      password-parameter: password      # password参数
      token-parameter: Authorization    # token请求头参数